openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: documentation of the Cook Book application
tags: # теги, що ви будете використовувати
  - name: Recipes
    description: Cookbook woth different recipes
  - name: Auth
    description: Authentication operations
servers:
  - url: http://localhost:3000
paths: # тут будуть посилання на ендпоінти

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
